### ISSUE TITLE
all rooms generate the following error : 'RoomMessagesError' object has no attribute 'chunk'

### ISSUE THREAD

**Issue by PatrickJRed** [MeowOrange/matrix-archive#6]
Hello again,

no matter the room i am trying to archive i get the following error:
'RoomMessagesError' object has no attribute 'chunk'
EXITCODE:1

Greetings PJ
running in docker "orangemeow/matrix-archive:1.6"

**Comment by MeowOrange** [comment]
fixed. Try orangemeow/matrix-archive:1.7. looks it's caused by matrix server upgrading because I reproduced this issue after upgrading my synapse server.

**Comment by PatrickJRed** [comment]
Tag 1.7 seem to have fixed it.
Thanks :)
